##################################################
# https://minecraft.fandom.com/wiki/Game_rule
##################################################

worlds:
  lobby:
    doDaylightCycle: false
    fallDamage: false
    keepInventory: true
    randomTickSpeed: 0
  # support regex
  world-user-.*:
    keepInventory: true