name: ASPGamerule
version: '${project.version}'
main: com.arknesia.plugin.Main
api-version: '1.20'
commands:
  aspg:
    description: Show plugin information or reload the configuration
    usage: /<command> [reload]